In [1]:
# all materials at https://github.com/fedhere/PyBOOT

In [37]:
# if you're using Python 2, import print function (module, basically a python object) from future
# imports should always be at the top
from __future__ import print_function
import numpy as np
# if you use instead 'from numpy import *', you overwrite variables from other packages
# we never want to do this; we want to "preserve the namespace"

In [38]:
print( "Hello World!")

Hello World!


In [77]:
# let's begin with variables

stringVariable = 'Hello World!'

In [78]:
print(stringVariable)

Hello
 World!


In [41]:
intVariable = 3
print(intVariable)

3


In [42]:
floatVariable = 3.
print(floatVariable)

3.0


In [43]:
type(floatVariable)

float

In [44]:
# if you multiple different types, you'll get back the most complex type
floatVariable * intVariable

9.0

In [45]:
# formatting print
print("let's print an integer %.2f and a float %s"%(intVariable, floatVariable)) # printing a string # .2f tells decimal places
# there's another way that's more sophisticated:
print("let's print and integer {:d} and a float {:f} and an integer again {:d}"\
      .format(intVariable, floatVariable, intVariable))

# if you want to print the same value a bunch of times in your string, this is a much better method
print("let's print and integer {x} and a float {y} and an integer again {x}"\
      .format(x=intVariable, y=floatVariable))
# you can also refer to the variables by the order in which you've passed them
print("let's print and integer {0:d} and a float {1:5f} and an integer again {0:f}"\
      .format(intVariable, floatVariable))

let's print an integer 3.00 and a float 3.0
let's print and integer 3 and a float 3.000000 and an integer again 3
let's print and integer 3 and a float 3.0 and an integer again 3
let's print and integer 3 and a float 3.000000 and an integer again 3.000000


In [46]:
# boolean operators
isinstance(intVariable, float) > 0

False

In [48]:
if True + False:
    print ("it is!")
    
# array of booleans > helpful to use math for comparison instead of string operators
np.array([True, True, False]) * np.array([True, False, True]) # comes in handy for broadcasting arrays, which we'll see later

it is!


array([ True, False, False], dtype=bool)

In [49]:
if (1>0):
    print("it is!")
else:
    print("it ain't")

it is!


In [51]:
# lists are unstructured, hybrid containers, meaning the space occupied by each object inside is undetermined
# lists don't do a lot though; they don't have a lot of methods
# lists are nestable, meaning they can contain lists inside lists
aList = [0, 1, "Hello"]
type(aList)

list

In [52]:
aList.append("I'm a string")

In [53]:
aList

[0, 1, 'Hello', "I'm a string"]

In [54]:
aList + aList

[0, 1, 'Hello', "I'm a string", 0, 1, 'Hello', "I'm a string"]

In [55]:
aList[0]

0

In [57]:
aList[0] = "World"
aList[0][0] # you can index the letter within a string in the list

'W'

In [58]:
# but strings are immutable, unlike lists
aList[0][1] = 'p'

TypeError: 'str' object does not support item assignment

In [61]:
aTuple = (0,1)
print(type(aTuple))
# lists and tuples repeat themselves if you multiply them by a number
aTuple * 2

<class 'tuple'>


(0, 1, 0, 1)

In [65]:
print(np.array([0., 1., 2.])) #creating a list and casting it as an array
np.array([0., 1., 2.]) + 2 # we can sum the array to a number, and it adds them element by element

[ 0.  1.  2.]


array([ 2.,  3.,  4.])

In [66]:
# if you know the size of what you want to store, arrays are better
np.zeros(100, float) # this creates an empty array of 100

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [67]:
2**16 /2 -1

32767.0

In [68]:
aList[:3] # takes everything up to but not including the third index

['World', 1, 'Hello']

In [69]:
np.array(aList[:3]) #turned everything into strings because arrays can only contain a single type
# lists are less efficient than arrays, but they allow you to store hybrid variable types

array(['World', '1', 'Hello'], 
      dtype='<U5')

In [72]:
# arrays can be multidimensional
emptyAr = np.ones((10,20), int) # first argument is always the size, in this case a tuple
emptyAr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [73]:
emptyAr[0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [74]:
# look at the shape to make sure you're looking at the right axis
emptyAr.shape

(10, 20)

In [75]:
# arrays have a lot of methods
emptyAr.mean()

1.0

In [84]:
# string methods
stringVariable.strip().strip("!").split() # split will return list as broken up at the space

['Hello', 'World']

In [85]:
"~".join(stringVariable.strip().strip("!").split()) # rejoin with a tilde

'Hello~World'

In [88]:
"~".join(stringVariable.strip().strip("!").split()).lower().replace("l", "1.") # replacing a character does so everywhere

'he1.1.o~wor1.d'

In [95]:
# dictionaries are another way we can host objects
# makes retrieval easier by giving a name (key) to each object
dictVariable = {'k1': 1.0, 'k2': 2.0}
dictVariable['k3'] = 3.0 # adds a new key value pair to the dict
dictVariable

{'k1': 1.0, 'k2': 2.0, 'k3': 3.0}

In [93]:
dictVariable = {}
for i in range(10):
    dictVariable[i] = i**2
    
dictVariable

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}

In [114]:
# now let's talk about slicing and broadcasting
# arrays are efficient and flexible objects
np.random.seed(999)
anArray = np.random.randint(0, 30, 30).reshape(2, 15)

In [115]:
print(anArray)
anArray[:,0] # gives me everything along the rows but just the 0th element

[[ 0 28  5  1  8  1 27 25 19 16 13 21  8  8 16]
 [ 5  2 11 11 21 23  4 26  6 18  7  6 17  5 19]]


array([0, 5])

In [111]:
anArray[2:5,1:3]

array([[-0.85806707, -0.75977816],
       [ 0.4740131 , -1.70263337],
       [ 0.06924485,  0.84702407]])

In [117]:
# when I do math on an array, it operates on each element
anArray > 5

array([[False,  True, False, False,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [False, False,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True]], dtype=bool)

In [124]:
# give me out of the array only the places where the number is greater than 5
np.where(anArray[0] > 5)[0]

array([ 1,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [125]:
anArray.T # returns the array transposed

array([[ 0,  5],
       [28,  2],
       [ 5, 11],
       [ 1, 11],
       [ 8, 21],
       [ 1, 23],
       [27,  4],
       [25, 26],
       [19,  6],
       [16, 18],
       [13,  7],
       [21,  6],
       [ 8, 17],
       [ 8,  5],
       [16, 19]])

In [126]:
anArray.astype(float) # changes everything in the array into floats

array([[  0.,  28.,   5.,   1.,   8.,   1.,  27.,  25.,  19.,  16.,  13.,
         21.,   8.,   8.,  16.],
       [  5.,   2.,  11.,  11.,  21.,  23.,   4.,  26.,   6.,  18.,   7.,
          6.,  17.,   5.,  19.]])

In [176]:
"""EXERCISE:
create a numpy array containing numbers from 1 to 10
extract only even numbers with boolean operations
reverse it
make all those number odd (hint: you can use use range or np.arange to create the array)"""

box = np.arange(1, 11)
print(box)
box = np.where(box % 2)[0]
box = box[::-1]
print(box)

[ 1  2  3  4  5  6  7  8  9 10]
[8 6 4 2 0]
